#! /usr/bin/env python2
"""Usage: winrm SERVER PORT USER PASSWORD COMMAND

Run COMMAND on a remote machine that has a running WinRM server.

Arguments:
  SERVER      Host to contact
  PORT        Host port to contact
  USER        User login
  PASSWORD    User password
  COMMAND     Command to run

Options:
  -h --help   Print help
"""
import winrm
import sys

import docopt


def main():
    arguments = docopt.docopt(__doc__)
    server = arguments['SERVER']
    port = arguments['PORT']
    user = arguments['USER']
    password = arguments['PASSWORD']
    cmd = arguments['COMMAND']

    url = '{server}:{port}'.format(server=server, port=port)
    transport = {
        '5985': 'plaintext',
        '5986': 'ssl',
    }
    kwargs = {}
    kwargs['transport'] = transport.get(port)

    session = winrm.Session(url, auth=(user, password), **kwargs)
    # print cmd
    res = None
    try:
        res = session.run_cmd(cmd)
    except Exception as err:
        print err.message
    else:
        sys.stdout.write(res.std_out)
        sys.stderr.write(res.std_err)


if __name__ == '__main__':
    main()
